# This file was generated by GoReleaser. DO NOT EDIT.
cask "youtrack-tui" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "55e150334930e4812317a176ea3b3c9af8dcd7404b3c5ad974eed920840a2be3"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "ba82f588075c42adb2078064157589f87a1c8c03945593a0398f94039c0b5c77"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ab470fd016ca06572470be017349472bcc6aa388be6869de73e74e2b3d1574b4"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "621b319d967d8cc72003531aa55fb4f89711f9d99576600206b07d918bf32ad9"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-linux-amd64.tar.gz"
    end
  end

  name "youtrack-tui"
  desc "Read-only terminal UI for browsing YouTrack issues"
  homepage "https://github.com/omartelo/youtrack-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "youtrack-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/youtrack-tui"]
    end
  end

  # No zap stanza required
end
