# This file was generated by GoReleaser. DO NOT EDIT.
cask "youtrack-tui" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "f9160e1a9e19cc4ccf2bff2f89521c9c57e8603fe67060f4059d40d5dee3d9ae"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/omartelo/youtrack-tui"
    end
    on_arm do
      sha256 "e3e13a5d4b64c42815f852b245078c85a5d60aaa9e8388f523f9f18158085033"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/omartelo/youtrack-tui"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a60f33d5262a1a3c144ee3c539e8c404d93986d8aa96472f778d9f789733461"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-linux-amd64.tar.gz",
        verified: "github.com/omartelo/youtrack-tui"
    end
    on_arm do
      sha256 "44ea97cb2bb91c025e3cf6008e8a2e500abed0c7a6b97d1889ac0cb1b804e29d"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-linux-arm64.tar.gz",
        verified: "github.com/omartelo/youtrack-tui"
    end
  end

  name "youtrack-tui"
  desc "Read-only terminal UI for browsing YouTrack issues"
  homepage "https://github.com/omartelo/youtrack-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "youtrack-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/youtrack-tui"]
    end
  end

  # No zap stanza required

end
