# This file was generated by GoReleaser. DO NOT EDIT.
cask "youtrack-tui" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "62f47451b890784d6d9ab686f4bad748e7cbcfc92ddeb09289d8a129708a6c46"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/omartelo/youtrack-tui"
    end
    on_arm do
      sha256 "1ee973ca329ebc3868ffa3fb339bdf42b165a99bc1393cc726067bf0b1198e89"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/omartelo/youtrack-tui"
    end
  end

  on_linux do
    on_intel do
      sha256 "8322cb7c776431eaf3465fbd21d27b7c70fb66f7299d85875fe16ad79bfe9c86"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-linux-amd64.tar.gz",
        verified: "github.com/omartelo/youtrack-tui"
    end
    on_arm do
      sha256 "f18d318d3f7b8aff74045ee1a745aa852fb79d9762e483b7b7f3ffc53bf1f899"
      url "https://github.com/omartelo/youtrack-tui/releases/download/v#{version}/youtrack-tui-#{version}-linux-arm64.tar.gz",
        verified: "github.com/omartelo/youtrack-tui"
    end
  end

  name "youtrack-tui"
  desc "Read-only terminal UI for browsing YouTrack issues"
  homepage "https://github.com/omartelo/youtrack-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "youtrack-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/youtrack-tui"]
    end
  end

  # No zap stanza required

end
